# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8232c5a03c8974d9f78445b46f39e73336bcfcb822daa70699db7f13495a9852d9b5178a2e1eb870fc0d43c2ab28c4386d2fd3226aa5585609f61c428b108cfd

test:
  secret_key_base: 3d6efd108dd92bfd697da5f9559b3d3cfdf83f6668eaf0beaa52ce2e1c9172c05008941904c210ca9ab955d56eb3a1683d1af7f86d85df3b72bb846204e36627

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
